version: "3"
services:

  outline:
    image: outlinewiki/outline:0.67.1
    command: ${OUTLINE_START_COMMAND}
    env_file: ./outline.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - production-ssl-disabled=${PRODUCTION_SSL_DISABLED}
      - FORCE_HTTPS=${FORCE_HTTPS}
      - COLLABORATION_URL=${COLLABORATION_URL}

  redis:
    image: redis
    env_file: ./outline.env
    expose:
      - 6379
    volumes:
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./outline.env
    expose:
      - 5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready -U user" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: outline

volumes:
  database-data:
